=== KendraLynn/Lab1WebAdv/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.lab1.com/menu"
    xmlns="https://www.lab1.com/menu"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xs:element name="lab1">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="servingTime" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="category" maxOccurs="unbounded" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="meals" />
                                        <xs:enumeration value="dinner" />
                                        <xs:enumeration value="drinks" />
                                        <xs:enumeration value="dessert" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="subCategory">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Item" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="description" type="xs:string"></xs:element>
                                                    <xs:element name="price">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:int">
                                                                <xs:minInclusive value="1"></xs:minInclusive>
                                                                <xs:maxInclusive value="75"></xs:maxInclusive>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KendraLynn/Lab1WebAdv/lab1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="lab1.xsl" type="text/xsl"?>
<lab1 xmlns="https://www.lab1.com/menu"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.lab1.com/menu menu.xsd">
    <servingTime name="lunch">
        <category>meals</category>
        <subCategory>
            <Item>
                <description>Nachos</description>
                <price>19</price>
            </Item>
            <Item>
                <description>Mac n Cheese</description>
                <price>15</price>
            </Item>
        </subCategory>
    </servingTime>

    <servingTime name="dinner">
        <category>meals</category>
        <subCategory>
            <Item>
                <description>Steak Dinner</description>
                <price>35</price>
            </Item>
            <Item>
                <description>Vegetarian Dish</description>
                <price>20</price>
            </Item>
        </subCategory>
    </servingTime>

    <servingTime name="drinks">
        <category>drinks</category>
        <subCategory>
            <Item>
                <description>Rum n Coke</description>
                <price>6</price>
            </Item>
            <Item>
                <description>Beer</description>
                <price>7</price>
            </Item>
        </subCategory>
    </servingTime>
    <servingTime name="dessert">
        <category>dessert</category>
        <subCategory>
            <Item>
                <description>Chocolate Pie</description>
                <price>8</price>
            </Item>
            <Item>
                <description>Cake</description>
                <price>4</price>
            </Item>
        </subCategory>
    </servingTime>
</lab1>
